spring:
    datasource:
        url: jdbc:mysql://${DB_HOST}/${DB_DATABASE}?useUnicode=true&character_set_server=utf8mb4
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            poolName: Hikari
            auto-commit: true
            minimum-idle: 1
            maximum-pool-size: 5
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        database: MYSQL
        generate-ddl: false
        show-sql: false
        open-in-view: false
        hibernate:
            ddl-auto: validate

---
spring.config.activate.on-profile: local, sandbox
spring:
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true

---
spring.config.activate.on-profile: test
spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
