spring:
    data:
        redis:
            host: 192.168.1.200
            port: 6379
            lettuce:
                pool:
                    max-active: 8
                    max-idle: 8
                    min-idle: 0
                    max-wait: 1ms
