name: Deploy-Production

on:
    push:
        branches:
            - "main"

env:
    REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
    IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
    IMAGE_TAG: ${{ github.sha }}
#    DEPLOYMENT: ${{ secrets.K8S_DEPLOYMENT }}
#    CONTAINER_NAME: ${{ secrets.K8S_CONTAINER_NAME }}

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        environment: sandbox

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Set up JDK 19
                uses: actions/setup-java@v3
                with:
                    java-version: '19'
                    distribution: 'adopt'

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Check ktlint format
                run: ./gradlew clean ktlintCheck

            -   name: Test with Gradle
                run: ./gradlew test
    build:
        name: Build
        runs-on: ubuntu-latest
        environment: production
        outputs:
            image: echo ${{ steps.build-image.outputs.image }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Docker Setup QEMU
                uses: docker/setup-qemu-action@v1.2.0

            -   name: Docker Setup Buildx
                uses: docker/setup-buildx-action@v1.6.0

            -   name: Build Docker image
                run: |
                    docker build \
                    --platform linux/arm64 \
                    --build-arg PHASE=${{ vars.PHASE }} \
                    -t $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG .

            -   name: Push Docker image
                run: docker push $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG

#       ArgoCd 적용
#    deploy:
#        name: Deploy
#        runs-on: ubuntu-latest
#        environment: production
#        needs:
#            - test
#            - build
#        steps:
#            -   name: Checkout
#                uses: actions/checkout@v3
#
#            -   name: Deploy k8s
#                uses: actions-hub/kubectl@master
#                env:
#                    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
#                with:
#                    args: set image deployment/$DEPLOYMENT $CONTAINER_NAME=$REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG

